#!/usr/bin/env node
// Cloud Functions can only deploy files inside functions/, so the canonical
// copies of the shared scoring logic (shared/) and the tunable system prompts
// (prompts/) are mirrored into functions/src before every build. Edit the
// originals, never the generated copies.
import { mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const sharedSrc = path.join(root, 'shared')
const promptsSrc = path.join(root, 'prompts')
const sharedOut = path.join(root, 'functions', 'src', 'shared')
const generatedOut = path.join(root, 'functions', 'src', 'generated')

const BANNER = '// GENERATED by scripts/sync-shared.mjs. Do not edit.\n'

async function syncShared() {
  await rm(sharedOut, { recursive: true, force: true })
  await mkdir(sharedOut, { recursive: true })

  const files = (await readdir(sharedSrc)).filter((f) => f.endsWith('.ts'))
  for (const file of files) {
    const body = await readFile(path.join(sharedSrc, file), 'utf8')
    await writeFile(path.join(sharedOut, file), BANNER + body)
  }
  return files.length
}

async function syncPrompts() {
  await mkdir(generatedOut, { recursive: true })

  const files = (await readdir(promptsSrc)).filter((f) => f.endsWith('.md')).sort()
  const entries = []
  for (const file of files) {
    const body = await readFile(path.join(promptsSrc, file), 'utf8')
    entries.push(`  ${JSON.stringify(path.basename(file, '.md'))}: ${JSON.stringify(body)},`)
  }

  const module = `${BANNER}// Source of truth: /prompts/*.md
export const PROMPTS = {
${entries.join('\n')}
} as const;

export type PromptName = keyof typeof PROMPTS;
`
  await writeFile(path.join(generatedOut, 'prompts.ts'), module)
  return files.length
}

const [sharedCount, promptCount] = await Promise.all([syncShared(), syncPrompts()])
console.log(`sync-shared: ${sharedCount} shared module(s), ${promptCount} prompt(s) -> functions/src`)
